name: C/C++ CI

on:
  push:
    branches: [ test_built ]
  pull_request:
    branches: [ test_built ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Run Makefile
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: make 
