name: C/C++ CI

on:
  push:
    branches: [ test_built ]
  pull_request:
    branches: [ test_built ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          
      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: cpp
          
      - name: Run Makefile
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: make 
