name: C/C++ CI

on:
  push:
    branches: [ test_built ]
  pull_request:
    branches: [ test_built ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.5, 2.6, 2.7]
    
    steps:
      
      # Install Binutils, Multilib, etc
      - name: Install C dev Tools
        run: |
          sudo apt-get update -qq 
          sudo apt-get install --assume-yes --quiet gcc-multilib
          sudo apt-get install -qq gcc-avr binutils-avr avr-libc
      
      # Install GCovr
      - name: Install GCovr
        run: |
          sudo pip install gcovr
          
      # Checkout the latest code
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          
      # Setup Ruby Testing Tools to do tests on multiple ruby version
      - name: Setup Ruby Testing Tools
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          
      # Install Ruby Testing Tools (Bundler version should match the one in Gemfile.lock)
      - name: Install Ruby Testing Tools
        run: |
          gem install rspec
          gem install rubocop -v 0.57.2
          gem install bundler -v "$(grep -A 1 "BUNDLED WITH" Gemfile.lock | tail -n 1)"
          bundle install
      
      # Build & Install Gem
      - name: Build and Install Gem
        run: |
          gem build ceedling.gemspec
          gem install --local ceedling-*.gem
      
      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: cpp
          
      - name: Run Makefile
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: make 
        
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
        
      # Perform the Unit Test
